name: Publish Package

on:
  push:
    branches:
      - main

jobs:
  check-commit:
    runs-on: ubuntu-latest
    outputs:
      valid_commit: ${{ steps.check_version.outputs.valid }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get commit message
        id: commit_message
        run: echo "MESSAGE=$(git log -1 --pretty=%B)" >> $GITHUB_ENV

      - name: Check if commit message matches version pattern
        id: check_version
        run: |
          if [[ "$MESSAGE" =~ ^V[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Valid commit message: $MESSAGE"
            echo "valid=true" >> $GITHUB_ENV
            echo "valid=true" >> $GITHUB_OUTPUT
          else
            echo "Commit message does not match version pattern. Skipping publish."
            echo "valid=false" >> $GITHUB_ENV
            echo "valid=false" >> $GITHUB_OUTPUT
          fi
        shell: bash

  publish-npm:
    needs: check-commit
    if: needs.check-commit.outputs.valid_commit == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm run publish_npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
